### ISSUE TITLE
Implementation on hardware

### ISSUE THREAD

**Issue by avdhootu27** [MarkNaeem/ros_controllers#3]
Hi,
How to use swerve_steering_controller with hardware?
On which topic does this controller publish desired velocities and positions?

**Comment by MarkNaeem** [comment]
swerve controller is just like any other controller. In order to use on hardware, you need to have a hardware_interface and joint_state for every joint you have. In our case, we have a velocity joint hardware_interface for the wheel joint and a position joint hardware_interface for its steering joint. 

I assume you already know how to implement such interfaces and connect them to your hardware as this is not the novelty of this package.

Thanks
