### ISSUE TITLE
Regarding joint_state data 

### ISSUE THREAD

**Issue by omkulkarni01** [MarkNaeem/ros_controllers#4]
Hi,
I just want to know that according to swerve_steering_controller gazebo is publishing the positions and velocities on the joint_state topic, so from where does gazebo is getting that data? 
And how does the swerve_steering _controller is sending desired positions and velocities data to gazebo?

**Comment by MarkNaeem** [comment]
Hello,
This issue is not related to the topic of the repository (the swerve controller itself). Please check gazebo documentation to learn more about it.

In order to know the answer to this question, you will need to get back to how ros control in general works. you need to have a joint_state and a  joint hardware_interface to do the reading and the writing for the joint (either in gazebo or for a real joint).

We need to keep the issues area only for errors and bugs in the package.

Thanks
